### ISSUE TITLE
Add possibily to configure the IRMA Base API URL and the API Version used

### ISSUE THREAD

**Issue by guillaumededrie** [quarkslab/irma-cli#2]
When I try to use a subdomain (ex: `api.irma.local`) in `address` key in the config file, http request are done to `api.irma.local/api/v1.1` (see: https://github.com/quarkslab/irma-cli/blob/master/irma/helpers.py#L62).

Adding the ability to configure will be more flexible for use:
```ini
[Server]
api_base_address=<api.…/10.0.…>
api_version=<1/1.1>
```

**Comment by ch0k0bn** [comment]
fix by 9f8397f3f0888c565895d804b334fbc625564eca
